

# .github/workflows/deploy.yml
name: Deploy Terraform via Temporal

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      # - name: Start Workflow
      #   run: go run starter.go

      - name: Start Temporal Workflow
        run: go run worker.go activities.go workflows.go  
        env:
          TEMPORAL_ADDRESS: http://172.172.245.99:8080

